get http://localhost:3002/api/feedback/rattingAvgAllFoods





###
,   {$group:{_id: '$_id', first: {"$rating":"$rating"} , total:{$sum : '$rating' } }} 
post http://localhost:3002/api/food

content-type: application/json
    {
        "name": "req.body.name",
        "categoryId":"req.body.categoryId",
        "info": "req.body.info",
        "order": 2
    }